### ISSUE TITLE
not reflected transaction result to testnet-3

### ISSUE THREAD

**Issue by wim-web** [ElixirProtocol/testnet-3-issue-tracker#12]
some validators realize that not reflected result to site from 2024-09-10T07:30:00Z

i try to mint too, but mock balance is still 0 after 10min
one user says it's not reflected after 1h

tx hash: 0x075f8c8b698ef4dfc2ded93fc80efc255c935fc3132189c9b8abb6e9bb56d1de

![スクリーンショット 2024-09-10 18 22 23](https://github.com/user-attachments/assets/45058061-c586-4523-b810-8d148b2ae30d)
![スクリーンショット 2024-09-10 18 22 46](https://github.com/user-attachments/assets/95c72b74-a2ad-485e-9e45-a6c16f54d99b)

reconnect wallet or clear cache doesnt help

**Comment by ajelixir** [comment]
this was due to a bad sepolia node. this has been resolved.
