### ISSUE TITLE
Average Uptime

### ISSUE THREAD

**Issue by quadro-network** [ElixirProtocol/testnet-3-issue-tracker#16]
Average Uptime is not displayed correctly in the dashboard.

![image](https://github.com/user-attachments/assets/8230a45a-906f-4beb-bbe1-e9022565ca63)

![image](https://github.com/user-attachments/assets/f7265cf4-680c-4ffa-9273-c0071f0084dd)

**Comment by ajelixir** [comment]
uptime has been revised.  this should no longer be an issue.
