### ISSUE TITLE
metrics endpoint response "Not Found" in 3.5.0

### ISSUE THREAD

**Issue by wim-web** [ElixirProtocol/testnet-3-issue-tracker#19]
![スクリーンショット 2024-10-09 2 38 59](https://github.com/user-attachments/assets/5d11b0fa-6ab6-4460-a325-814851c5a85a)

add "PROMETHEUS_MULTIPROC_DIR=./tests" to validator.env

![スクリーンショット 2024-10-09 2 40 22](https://github.com/user-attachments/assets/6893156e-55de-4b92-838d-7cc16ef6af83)

**Comment by ajelixir** [comment]
you can use `curl --location http://localhost:17690/metrics` to return the metrics data
