### ISSUE TITLE
Uptime Discrepancy: Node Log vs. Testnet Display

### ISSUE THREAD

**Issue by Nevquit** [ElixirProtocol/testnet-3-issue-tracker#20]
"The node log shows the uptime is 100, but https://testnet-3.elixir.xyz/ shows it as 40%."

Dokcer logs：
Important Note: You may see unexpected values for APY and Rewards. These features are currently under construction and may change at any time.

Yay!! It is working!!!! Great job!! You rock!!

Support Information:
    * SOFTWARE VERSION: 3.4.6
    * DISPLAY NAME: ak477
    * BENEFICIARY: 
    * VALIDATOR ADDRESS: 0x1a3089e605f040ea3064AE6f8dbB79f124d447F4
    * LAST DATAFRAME: 2024-09-29 22:00:34
    * LAST PROPOSAL: 2024-09-29 22:00:34
    * UPTIME: 100.000%

Status will update again in 60 seconds
https://testnet-3.elixir.xyz/
![image](https://github.com/user-attachments/assets/9bec24da-6f28-49e2-a3d7-7effdb163eed)

**Comment by ajelixir** [comment]
uptime improvements were recently deployed.  this should be resolved now
