### ISSUE TITLE
The command example is missing a backslash in docs

### ISSUE THREAD

**Issue by wim-web** [ElixirProtocol/testnet-3-issue-tracker#4]
For example, we copy and paste the sample code from https://docs.elixir.xyz/running-an-elixir-validator#optional-setting-a-restart-policy-for-your-validator then, it will result in an error.

![スクリーンショット 2024-08-30 19 42 08](https://github.com/user-attachments/assets/f7ac8987-9b6d-4b05-bdce-9c24286614ec)

**Comment by ajelixir** [comment]
The site has been updated
