### ISSUE TITLE
Incorrect calculation of UpTime + Unlimited Mock minting

### ISSUE THREAD

**Issue by YAMISHKA02** [ElixirProtocol/testnet-3-issue-tracker#5]
Uptime is showing the all time of node working/day - so there is only the percentage.
<img width="1699" alt="Снимок экрана 2024-08-31 в 00 23 57" src="https://github.com/user-attachments/assets/675881bf-ce07-416b-9a70-577157210bfb">

Also here can be unlimited MOCK minted in one transaction. I minted actually 10kk mock in one transaction. 
https://sepolia.etherscan.io/tx/0x22a7fce370b20f2bb7e6848456277e80bf6a4cb7edcccb233d4c95ee41bd966b

**Comment by ajelixir** [comment]
The UI is currently only using the daily uptime by design.  The value displayed in your screenshot seems appropriate for the data being returned from the api.

The unlimited minting issue has already been logged -see https://github.com/ElixirProtocol/testnet-3-issue-tracker/issues/1
